### ISSUE TITLE
listen for new hook filter:post.edit

### ISSUE THREAD

**Issue by barisusakli** [Schamper/nodebb-plugin-poll#16]
plugins.fireHook('filter:post.edit', {post: postData, uid: data.uid}, next);

**Comment by Schamper** [comment]
https://github.com/Schamper/nodebb-plugin-poll/commit/3a2145ef57707ec1621d58947d311f4338e5ec5e

Requires page refresh to view poll, need https://github.com/NodeBB/NodeBB/pull/4162 to fix.
