### ISSUE TITLE
Multiple polls & polls regular posts in a thread

### ISSUE THREAD

**Issue by Faldrian** [Schamper/nodebb-plugin-poll#18]
I just tried the plugin and the only way it would work in my 0.6.0-nodebb was when I inserted exactly *one* poll-markdown-block in the thread-opening-post.
Should I habe a second block in that post, then the second will override the first.
I can't edit the poll afterwards...
The poll won't work in answers to any thread, the markdown is not parsed or interpreted there.

These are some things I noticed when using this plugin - and I like the idea and would want this to be much more intuitive to use. :) Currently I have not much time... maybe I could work on those features and make PRs, but I wanted to discuss first. ;)

**Comment by Schamper** [comment]
It currently only allows one poll per thread and only in the first post, by design. This was done intentionally. 

This plugin is really out of date and I should really work on it again but a limited amount of free time is holding me back.

**Comment by Faldrian** [comment]
I understand, I know that situation. :)
Is there any roadmap or ideas in which direction this could be developed, so other developers could participate and take on specific tasks?

**Comment by Schamper** [comment]
Generally the points in the readme file. I'd really like to rewrite this plugin from the ground up since a lot of NodeBB has changed since I first wrote it.

**Comment by Faldrian** [comment]
I'm looking forward to the rewrite (some time...) :)

Am 24. März 2015 13:04:08 MEZ, schrieb Erik Schamper <notifications@github.com>:

**Comment by Schamper** [comment]
Only one poll in the first post per thread is supported by design. Unless some great arguments can be provided as to why otherwise should be supported this will remain to be the situation.
