### ISSUE TITLE
when you save the text is not new reloaded. and poll is not use.

### ISSUE THREAD

**Issue by ogerly** [Schamper/nodebb-plugin-poll#28]
So the tool is running.
following error, I've found.
the poll will be created.
when you save the text is not new reloaded. and poll is not use.
Here are the screenshots
https://community.nodebb.org/topic/6186/poll-tool/6

**Comment by Schamper** [comment]
This is fixed in the version over at the development branch. When it's published and you still encounter this issue you can reopen it.
