### ISSUE TITLE
The max parameter isn't working under NodeBB 0.8.2

### ISSUE THREAD

**Issue by astucieuxzephyr** [Schamper/nodebb-plugin-poll#33]
Hi,
Under NodeBB 0.8.2, when I'm doing this : 

    [poll title="titrepoll" max="2"]
    - Réponse A : jaime un peu
    - Réponse B : jaime beaucoup
    - Réponse C : jadore
    - Réponse D : je naime pas
    [/poll]

The max parameter doesn't change anything : I can only vote for one option.

**Comment by Schamper** [comment]
Fixed in latest version

**Comment by astucieuxzephyr** [comment]
Thank you very much :+1:
