### ISSUE TITLE
Broken user images

### ISSUE THREAD

**Issue by shaaati** [Schamper/nodebb-plugin-poll#40]
When clicking on the vote count for a poll option a modal dialog pops up showing the users who voted for this option. However, the user images are not loaded correctly. The html created by the plugin shows that no link to a user picture is included:
```
<a href="/user/shaaati">
    <img class="poll-view-result-avatar" src="">
</a>
```

**Comment by Schamper** [comment]
I assume you're on NodeBB 0.9.x? I'm currently in the process of updating this plugin for that version.

**Comment by shaaati** [comment]
Yes, I'm on version 0.9.1. Great to hear that you are working on this plugin again. :)

**Comment by Schamper** [comment]
This is fixed in the version over at the development branch.
