### ISSUE TITLE
poll sometimes not working

### ISSUE THREAD

**Issue by Pappmann** [Schamper/nodebb-plugin-poll#43]
after creating new poll, there is showing only the code instead of poll

**Comment by Schamper** [comment]
I suppose you're using the version on npm/master branch?

**Comment by Pappmann** [comment]
Yes, im using latest nodebb version 0.9.3 and plugin installed from admin panel.

**Comment by Schamper** [comment]
This is probably fixed in the version over at the development branch. When it's published and you still encounter this issue you can reopen it.
