### ISSUE TITLE
when comes update to master branch?

### ISSUE THREAD

**Issue by Pappmann** [Schamper/nodebb-plugin-poll#52]
afer every upgrade of nodebb i have to copy the poll plugin from my local drive to fix the language, when is a new version is comming out? Or please accept pull requests to master branch!

**Comment by Schamper** [comment]
I'll get it done soon. The problem currently is that polls made with the previous version of the plugin won't work anymore. I still need to write a quick updater for that before I can actually release a new version.

**Comment by xulture** [comment]
few days ago when i tried upgrading to nodebb 1.x.x, forum kept crash-restarting because of nodebb-plugin-poll (disabling it fixes the issue, but I don't want to upgrade to 1.x.x without the poll).

Any chance that development branch is compatible with 1.x.x?

**Comment by Schamper** [comment]
@xulture I haven't checked yet. Were there any errors?

**Comment by xulture** [comment]
Hmm I just did upgrade again, to get the error message, alas it doesn't fail anymore.. :-)

**Comment by Nisthar** [comment]
@xulture Did it worked in 1.x.x ?

**Comment by xulture** [comment]
I haven't tested poll plugin, but nodebb upgrade works without errors (my problems were related to outdated version of imgbed plugin)

**Comment by Nisthar** [comment]
Ok. I am using 0.9.4 veriosn. In my case, the polling is not working. It doesn't parse the post and outputs the code of the poll as it is.
!(http://i.imgur.com/1DxarSH.jpg)

**Comment by Schamper** [comment]
Closing as it seems like the issue was not related to poll plugin. If you have any other problems, open a new issue.

**Comment by Nisthar** [comment]
@Schamper So its normally working. right?

I thought its outdated.

**Comment by Schamper** [comment]
Thought this issue was about the update error, heh. Anyway, still keeping this closed as it's not really an issue and is planned.
