### ISSUE TITLE
Can't get it to work in my 0.9.4 version

### ISSUE THREAD

**Issue by Nisthar** [Schamper/nodebb-plugin-poll#53]
Hi,
Its just saving the raw text when i tried to add the polling.

http://i.imgur.com/W00rCJB.jpg

**Comment by Schamper** [comment]
Did you enable it.

**Comment by Nisthar** [comment]
@Schamper Yes. I enabled it in the plugins section,

My quoting also have some problem. Its parsing and just outputting the text with ">" infront of it. I think both these issues are similar.

**Comment by Nisthar** [comment]
This is what i am getting (http://i.imgur.com/1DxarSH.jpg)

**Comment by Schamper** [comment]
Are you using the development branch?

**Comment by Nisthar** [comment]
@Schamper I installed from the ACP. Don't know if its development branch. 

Must be master branch.

**Comment by Schamper** [comment]
Download from here and place in `node_modules` folder: https://github.com/Schamper/nodebb-plugin-poll/tree/development

**Comment by Nisthar** [comment]
@Schamper Ok. Let me try it now.

**Comment by Nisthar** [comment]
@Schamper Checked it. Noticed changes in the ACP section of the plugin. Not no changes in the post
![](http://i.imgur.com/76CSSBa.jpg)

**Comment by Schamper** [comment]
Did you try making a new poll?

**Comment by Nisthar** [comment]
@Schamper I tried editing a current topic and adding the poll in it.

**Comment by Schamper** [comment]
Don't think editing is currently supported. Try making a new one.

**Comment by Nisthar** [comment]
@Schamper Ok. BTW can i create poll for normal posts (not topics) ?

**Comment by Schamper** [comment]
No. By design, polls are only allowed in the first post of a topic.

**Comment by Nisthar** [comment]
@Schamper Oh Ok. Thats desirable. Let me try it.

**Comment by Nisthar** [comment]
@Schamper The UI is working now. But the vote buttons are not doing anything.
