### ISSUE TITLE
Version 0.2.1 broken?

### ISSUE THREAD

**Issue by huegelc** [Schamper/nodebb-plugin-poll#62]
Hi,

after updating the plugin from 0.2.0 to 0.2.1 I get an error when clicking on the poll icon in the composer:

`Error Invalid request` 

I can´ t see any error messages in the log though.

**Comment by Schamper** [comment]
Update to 0.2.2 and try again

**Comment by Olegatro** [comment]
I have the same problem on 0.2.2 (just installed plugin on the latest nodebb version - 1.0.3)

**Comment by Schamper** [comment]
Are you logged in? Where are you clicking on the icon? As in, what category? In a topic?

When you're in a spot where it doesn't work, can you execute the following code snippet in your browser JavaScript console and report back here with what is printed out:
```
require(['composer'], function(c) {console.log(composer.posts[composer.active].cid);});
```

**Comment by Olegatro** [comment]
Oh, sorry, works!
I have not noticed that the poll can be attached only to the first post.
The error is came up, when I trying add poll to the second post in the topic.

I think, will be good disable btn (disabled state and cursor style not-allowed), when somebody trying click on the btn in the second post.

**Comment by Schamper** [comment]
Unfortunately that's a lot harder than it's worth, at the moment at least. I've since changed the button click flow though, so the error should at least be clearer.
