### ISSUE TITLE
User voted this answer bug

### ISSUE THREAD

**Issue by exomarty** [Schamper/nodebb-plugin-poll#67]
Only 2 votes. But many people appears

https://i.gyazo.com/c05504a1a690cdfc41f3d7bdb2f797eb.png

**Comment by Schamper** [comment]
What do the poll results say how many people voted? I may need you to run some DB queries for me to diagnose this.

**Comment by exomarty** [comment]
I think vote counts are ok. Just the user listing seems bugged
Let me know that queried

**Comment by exomarty** [comment]
any update on this issue?

**Comment by Schamper** [comment]
Sorry, not yet. Looked at the code in the meantime and didn't see a clear reason as to why this would happen. If you can provide me with the poll ID (check the `data-poll-id` data attribute on the poll view `div`) I can prepare some queries for you. What DB are you using?

**Comment by exomarty** [comment]
Sure
Here is an example
https://exo.do/topic/24984/encuesta-verano-o-invierno

**Comment by exomarty** [comment]
Mongo db

**Comment by Schamper** [comment]
I already spotted the issue. It looks like you (somehow, I believe I disabled it) have a merged data structure for the previous version of the poll plugin and the current version. 

I'm closing this issue because it's not necessarily an issue with this version of the poll plugin, and it shouldn't happen to any polls created exclusively with this version of the poll plugin. If it does, you can notify me and I'll re-open.

Meanwhile, to fix this particular issue, you'll have to edit some database entries. Specifically `poll:15` and `poll:15:options:[0-5]`. (so `options:0`, `options:1` etc.) For some there will be a `votecount` and `voteCount` key. The correct data must go in `voteCount`.

**Comment by exomarty** [comment]
I will check the db but the issue happens with new polls too. Thanl you

**Comment by Schamper** [comment]
Can you link to a new poll?

**Comment by exomarty** [comment]
here is your link
https://exo.do/topic/25159/test

**Comment by Schamper** [comment]
Very weird, but I can't find any reason as to how this can happen. When searching for the (incorrect) lowercase attributes in the code, the only results are CSS class names.
```
⟩ git grep votecount
public/js/poll/view.js:                 el.find('.poll-result-votecount span').text(option.voteCount);
public/js/poll/view.js:                 view.dom.resultsPanel.off('click').on('click', '.poll-result-votecount', function(e) {
templates/poll/view/results.tpl:        <a class="poll-result-votecount" href="#">

⟩ git grep pollid

```

So something seems to be wrong with your installation. Maybe you somehow have multiple versions installed? Something `npm link`'d?

**Comment by exomarty** [comment]
must be something with the db
i can run any query you tell me

just removed the plugin and installed again from package manager

other weird issue happens now is that instead of appearing correct poll answers it load answers from another old polls or mix them O_O

**Comment by exomarty** [comment]
Well found your issue
you changed your global key name on some update so old users been rewriting old polls :(

I solved with database editing on new nextPollId but plugin should have some checking on existing polls

![screenshot_2](https://cloud.githubusercontent.com/assets/10746278/19149457/24efc82e-8bc2-11e6-8575-ce9dddda0a5b.png)

**Comment by Schamper** [comment]
I did change it, but it shouldn't be possible for old users to still use that. The use of those keys are restricted to server side code, on which the client version (or the age of a user account) can't (or at least should) have no impact.

Previously, I showed some text saying that old polls were not supported (and they still shouldn't be), but I think they now just silently fail. It should be impossible for new polls to ever use those old keys.

**Comment by exomarty** [comment]
new plugin dont use old keys,  but i had polls on my forum, 478 polls
if new count begins in 0, news polls been overwriting old ones till it reach 478, now was on 30 already

**Comment by Schamper** [comment]
Hm I see now... Honestly not something that I thought about before :( sorry for the issues in that case. I might have an idea for a fix, which is to add the old poll ID counter to the new poll ID counter in an update script.

**Comment by exomarty** [comment]
that would work, thank you :)

**Comment by exomarty** [comment]
i will delete the key in my case so i doesnt increase it again if you update it wht that script in the future
