### ISSUE TITLE
no language switch

### ISSUE THREAD

**Issue by Pappmann** [Schamper/nodebb-plugin-poll#81]
Using Nodebb 1.4.4 english language although german is activated.

**Comment by Pappmann** [comment]
for temporarily fix i renamed the language folder from "de" to "en_GB"

**Comment by Schamper** [comment]
Weird, I wonder if anything changed in the way NodeBB handles languages...

**Comment by pczbq806** [comment]
Me too. My NodeBB is in Chinese.
I see NodeBB language folder named zh-CN, nodebb-plugin-poll in the language folder named zh_CN.

**Comment by Schamper** [comment]
Works fine for me on latest NodeBB.
