### ISSUE TITLE
Can not create a poll

### ISSUE THREAD

**Issue by suparomana** [Schamper/nodebb-plugin-poll#84]
Hi,

i'm using the poll-plugin with nodebb 1.4.6 and the nodebb-plugin-composer-redactor 2.0.6. When I open a new thread I see the button "create a poll" but after a click nothing happens and I can see no errors in the browser console. I tried to reinstall the poll-plugin, but the result is the same.

Thank you for looking into this.

Best Regards,
Chris

**Comment by Schamper** [comment]
Works on the latest version.
