### ISSUE TITLE
Can not create poll in already created topic

### ISSUE THREAD

**Issue by sosojni** [Schamper/nodebb-plugin-poll#85]
You can reproduce this error by creating new topic. Edit first (and only) post and try to insert poll. You get this error: Can only add poll in main post.

**Comment by Schamper** [comment]
Which composer are you using?

**Comment by sosojni** [comment]
Default one (nodebb-plugin-composer-default)
And i think i found reason why it is not working.
Function composer.editPost in this file: https://github.com/NodeBB/nodebb-plugin-composer-default/blob/master/static/lib/composer.js is not pushing "cid" which is needed in function "composerBtnHandle" in this file: https://github.com/Schamper/nodebb-plugin-poll/blob/master/public/js/poll/creator.js

**Comment by Schamper** [comment]
Think you might be able to create a PR for this?

**Comment by sosojni** [comment]
I'm not sure to be completely honest.
I'm really new to nodejs and nodebb so i don't really know "hows" and "whys" of the whole system. Is missing cid problem with composer? Should composer always send it? Or is asking for cid something that poll plugin should not insist on? You know...that kind of philosophical questions are my big problem :)
