### ISSUE TITLE
Poll table header permission text duplicates on copy permissions from category

### ISSUE THREAD

**Issue by Joykiller** [Schamper/nodebb-plugin-poll#86]
Duno if this is still supported by the developer of this plugin, but I found a bug Which I will also report on github, When copying permissions from a category it duplicate Create POLL #privileges > div > table:nth-child(2) > thead > tr:nth-child(3) > th:nth-child(17) 

![screenshot from 2017-07-27 17-45-37](https://user-images.githubusercontent.com/13190088/28697858-e837365a-72f3-11e7-9d79-6fd696001e2f.png)

**Comment by Joykiller** [comment]
PS Bug is duplicated on EVERY category.

**Comment by Joykiller** [comment]
TEMP FIX
Quick fix, is when you get done with creating your forum categories etc when there is header duplicates just disable the poll, restart forum then re-enable poll plugin and restart and it fixes the issue

**Comment by Schamper** [comment]
Lol, that's an interesting and amusing bug. I'll see if there's something I can do about it soon. In the meantime, if you figure it out before me, feel free to submit a PR.

**Comment by Schamper** [comment]
Hm what exactly are you doing? If I create a new clean category, go to the privileges tab and use "copy from category", I don't get any duplicate permissions. What version of NodeBB are you using?

**Comment by Schamper** [comment]
Try if v0.2.14 works.

**Comment by Joykiller** [comment]
will do, it was replicated for me by cloning a category and perms with poll enabled as plugin.

**Comment by barisusakli** [comment]
This was a bug in nodebb core
