### ISSUE TITLE
NodeBB reports latest plugin version is 2.15

### ISSUE THREAD

**Issue by jimmykane** [Schamper/nodebb-plugin-poll#91]
HI there, 

NodeBB reports latest plugin version is 2.15

<img width="834" alt="screen shot 2017-11-20 at 20 43 00" src="https://user-images.githubusercontent.com/1268723/33038000-85bf8f04-ce33-11e7-92af-ac140ce83f00.png">

**Comment by Schamper** [comment]
That is correct, what's the problem?

**Comment by jimmykane** [comment]
@Schamper maybe I am confused with the releases then.

**Comment by jimmykane** [comment]
<img width="824" alt="screen shot 2017-11-20 at 20 49 22" src="https://user-images.githubusercontent.com/1268723/33038259-52aa8992-ce34-11e7-87d3-0945315fa719.png">

**Comment by Schamper** [comment]
0.2.15 is the latest version, which includes the fixes from the recent PR. Releases on Github is just something I can add manually. It allows you to download a zip of the repository at that specific version. However, I didn't see any added value for this so I stopped doing that. The version that is on NPM is leading, and is what you install through NodeBB.

**Comment by jimmykane** [comment]
Right, too much used to bitbucket lately. Mind caring why when I press the poll icon when creating a new thread and no console message is there nothing happens? 

btw sorry for the fuzz.

**Comment by Schamper** [comment]
No idea, that's way too generic of a description, sorry.

**Comment by jimmykane** [comment]
fyi it was 'allow guests to view polls', which was set to on.
